BINDIR   := bin
VERSION  ?= v0.0.0-dev
COMMIT   ?= $(shell git rev-parse --short HEAD 2>/dev/null || echo unknown)
LDFLAGS  := -s -w \
  -X github.com/zippo1908/agentcell/internal/version.Version=$(VERSION) \
  -X github.com/zippo1908/agentcell/internal/version.Commit=$(COMMIT)

BINARIES := celld git-broker cell-runtime cellctl

.PHONY: all build $(BINARIES) test vet fmt-check lint clean web web-install

all: build

build: $(BINARIES)

$(BINARIES):
	CGO_ENABLED=0 go build -trimpath -ldflags '$(LDFLAGS)' -o $(BINDIR)/$@ ./cmd/$@

# cell-runtime is bind-mounted read-only into arbitrary container images,
# so it must always be a static linux/amd64 build regardless of the host.
.PHONY: build-runtime-static
build-runtime-static:
	CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -trimpath -ldflags '$(LDFLAGS)' \
	  -o $(BINDIR)/cell-runtime-linux-amd64 ./cmd/cell-runtime

# The UI is embedded into celld; build it before the Go binaries when it
# changed. dist/ is committed so `go build` works without Node.
web-install:
	cd web && pnpm install --frozen-lockfile

web:
	cd web && pnpm build

# Generation is single-source: the Go types are the truth, and both copies
# of the CRDs are outputs. Two hand-maintained copies had already drifted,
# and hand-edited YAML is where a validation rule quietly disappears.
CONTROLLER_GEN ?= go run sigs.k8s.io/controller-tools/cmd/controller-gen@v0.16.5

generate:
	@printf '// Code generated by controller-gen. DO NOT EDIT.\n' > .boilerplate.tmp
	$(CONTROLLER_GEN) object:headerFile=.boilerplate.tmp paths=./api/v1alpha1/...
	@rm -f .boilerplate.tmp
	$(CONTROLLER_GEN) crd paths=./api/v1alpha1/... output:crd:artifacts:config=config/crd
	cp config/crd/*.yaml deploy/charts/agentcell/crds/

# Fails if the committed output does not match what the types produce, so a
# field added to a struct cannot ship without the schema that stores it.
verify-generate: generate
	@git diff --exit-code -- api/v1alpha1 config/crd deploy/charts/agentcell/crds \
	  || { echo; echo "generated files are stale — run 'make generate' and commit"; exit 1; }

test:
	go test ./...

vet:
	go vet ./...

fmt-check:
	@out="$$(gofmt -l .)"; if [ -n "$$out" ]; then echo "gofmt needed:"; echo "$$out"; exit 1; fi

lint: fmt-check vet

clean:
	rm -rf $(BINDIR)
