BINDIR   := bin
VERSION  ?= v0.0.0-dev
COMMIT   ?= $(shell git rev-parse --short HEAD 2>/dev/null || echo unknown)
LDFLAGS  := -s -w \
  -X github.com/zippo1908/agentcell/internal/version.Version=$(VERSION) \
  -X github.com/zippo1908/agentcell/internal/version.Commit=$(COMMIT)

BINARIES := celld git-broker cell-runtime cellctl

.PHONY: all build $(BINARIES) test vet fmt-check lint clean web web-install

all: build

build: $(BINARIES)

$(BINARIES):
	CGO_ENABLED=0 go build -trimpath -ldflags '$(LDFLAGS)' -o $(BINDIR)/$@ ./cmd/$@

# cell-runtime is bind-mounted read-only into arbitrary container images,
# so it must always be a static linux/amd64 build regardless of the host.
.PHONY: build-runtime-static
build-runtime-static:
	CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -trimpath -ldflags '$(LDFLAGS)' \
	  -o $(BINDIR)/cell-runtime-linux-amd64 ./cmd/cell-runtime

# The UI is embedded into celld; build it before the Go binaries when it
# changed. dist/ is committed so `go build` works without Node.
web-install:
	cd web && pnpm install --frozen-lockfile

web:
	cd web && pnpm build

# Generation is single-source: the Go types are the truth, and both copies
# of the CRDs are outputs. Two hand-maintained copies had already drifted,
# and hand-edited YAML is where a validation rule quietly disappears.
CONTROLLER_GEN ?= go run sigs.k8s.io/controller-tools/cmd/controller-gen@v0.16.5

generate:
	@printf '// Code generated by controller-gen. DO NOT EDIT.\n' > .boilerplate.tmp
	$(CONTROLLER_GEN) object:headerFile=.boilerplate.tmp paths=./api/v1alpha1/...
	@rm -f .boilerplate.tmp
	$(CONTROLLER_GEN) crd paths=./api/v1alpha1/... output:crd:artifacts:config=config/crd
	cp config/crd/*.yaml deploy/charts/agentcell/crds/

# Fails if the committed output does not match what the types produce, so a
# field added to a struct cannot ship without the schema that stores it.
verify-generate: generate
	@git diff --exit-code -- api/v1alpha1 config/crd deploy/charts/agentcell/crds \
	  || { echo; echo "generated files are stale — run 'make generate' and commit"; exit 1; }

test:
	go test ./...

vet:
	go vet ./...

fmt-check:
	@out="$$(gofmt -l .)"; if [ -n "$$out" ]; then echo "gofmt needed:"; echo "$$out"; exit 1; fi

# preflight is what CI runs, before CI runs it.
#
# Three commits went to main red because the checks lived only in CI: gofmt
# on files I had edited, and a web lockfile that no longer matched
# package.json. Both are instant locally and neither is something to
# remember — so they stop being something to remember.
# chart-check needs helm; skipped with a word rather than silently when it is
# not installed, because "checks passed" must never mean "checks not run".
chart-check:
	@command -v helm >/dev/null 2>&1 \
	  && ./deploy/charts/agentcell/lint.sh \
	  || echo "chart-check SKIPPED: helm is not installed"

preflight: fmt-check vet test verify-generate web-lock-check web-check chart-check
	@echo "preflight OK"

# web-lock-check fails the same way CI does, for the same reason: a
# dependency added to package.json without updating the lockfile makes
# `pnpm install --frozen-lockfile` refuse, and every later step is skipped.
web-lock-check:
	@cd web && pnpm install --frozen-lockfile --lockfile-only >/dev/null 2>&1 || { \
	  echo "web/pnpm-lock.yaml is out of sync with package.json — run: cd web && pnpm install"; exit 1; }

# web-check is what CI's web job runs. `vite build` does NOT typecheck, so
# building locally and calling it verified is exactly how a type error
# reaches main — which is how one did.
web-check:
	@cd web && pnpm exec tsc --noEmit && pnpm build >/dev/null

lint: fmt-check vet

clean:
	rm -rf $(BINDIR)
